Traceback (most recent call last):
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/saved_ours/train_bonsai.py", line 249, in <module>
    main(vars(args))
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/saved_ours/train_bonsai.py", line 218, in main
    data = load_dataset(args["ds"].lower(), "/hdfs1/Data/Shubhajit/Project/Bonsai/datasets")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/saved_ours/train_bonsai.py", line 46, in load_dataset
    data = torch.load("/hdfs1/Data/Shubhajit/Project/CoPart-GNN/dataset/ogbn-products/saved/community_data.pt", map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/bonsai_env/lib/python3.12/site-packages/torch/serialization.py", line 1524, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, [1mdo those steps only if you trust the source of the checkpoint[0m. 
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL torch_geometric.data.data.DataEdgeAttr was not an allowed global by default. Please use `torch.serialization.add_safe_globals([torch_geometric.data.data.DataEdgeAttr])` or the `torch.serialization.safe_globals([torch_geometric.data.data.DataEdgeAttr])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
Traceback (most recent call last):
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/saved_ours/train_bonsai.py", line 249, in <module>
    main(vars(args))
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/saved_ours/train_bonsai.py", line 219, in main
    data_syn = load_syn_dataset(args["ds"], args["tf"], args["sr"], data["scaler"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/saved_ours/train_bonsai.py", line 56, in load_syn_dataset
    data_syn = torch.load(path, map_location="cpu", weights_only=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/bonsai_env/lib/python3.12/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/bonsai_env/lib/python3.12/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hdfs1/Data/Shubhajit/Project/Bonsai/bonsai_env/lib/python3.12/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/hdfs1/Data/Shubhajit/Project/Bonsai/saved_ours/products-0.3/data_m_0.9.pt'
